version: "3"
services:
  rlproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost:5000/rlproxy:latest
    ports:
      - "7070:7070"
    restart: always
    container_name: rlproxy
